webtalk_init -webtalk_dir D:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.sim/sim_1/behav/xsim/xsim.dir/test_camera_controller_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Aug 19 16:38:12 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "de015cd6-bc99-43b4-ad83-a8950f8d0c40" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1586c46ca0ad468ebb585d12d0c5fbe9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "26" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 2600X Six-Core Processor           " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3593 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "221515063333 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1404.17_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15808_KB" -context "xsim\\usage"
webtalk_transmit -clientid 220682463 -regid "" -xml D:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.sim/sim_1/behav/xsim/xsim.dir/test_camera_controller_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.sim/sim_1/behav/xsim/xsim.dir/test_camera_controller_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.sim/sim_1/behav/xsim/xsim.dir/test_camera_controller_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
