# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.srcs/sources_1/ip/sys_pll/sys_pll.xci
# IP: The module: 'sys_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.gen/sources_1/ip/sys_pll/sys_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.gen/sources_1/ip/sys_pll/sys_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.gen/sources_1/ip/sys_pll/sys_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.srcs/sources_1/ip/sys_pll/sys_pll.xci
# IP: The module: 'sys_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.gen/sources_1/ip/sys_pll/sys_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.gen/sources_1/ip/sys_pll/sys_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.gen/sources_1/ip/sys_pll/sys_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
