# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.srcs/sources_1/ip/window_shift_ram/window_shift_ram.xci
# IP: The module: 'window_shift_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.gen/sources_1/ip/window_shift_ram/window_shift_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'window_shift_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.srcs/sources_1/ip/window_shift_ram/window_shift_ram.xci
# IP: The module: 'window_shift_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.gen/sources_1/ip/window_shift_ram/window_shift_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'window_shift_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
