# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.srcs/sources_1/ip/edge_detector_fifo/edge_detector_fifo.xci
# IP: The module: 'edge_detector_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.gen/sources_1/ip/edge_detector_fifo/edge_detector_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'edge_detector_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.gen/sources_1/ip/edge_detector_fifo/edge_detector_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'edge_detector_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.gen/sources_1/ip/edge_detector_fifo/edge_detector_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'edge_detector_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.srcs/sources_1/ip/edge_detector_fifo/edge_detector_fifo.xci
# IP: The module: 'edge_detector_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.gen/sources_1/ip/edge_detector_fifo/edge_detector_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'edge_detector_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.gen/sources_1/ip/edge_detector_fifo/edge_detector_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'edge_detector_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/User/FPGA Projects/hdmi_test_v2/hdmi_test_v2.gen/sources_1/ip/edge_detector_fifo/edge_detector_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'edge_detector_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
